{{- if not .Values.existingConfigSecret.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authentik-provisioner.fullname" . }}
  labels:
    {{- include "authentik-provisioner.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
