{{- if .Values.authentik.token.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik-provisioner.fullname" . }}-token
  labels:
    {{- include "authentik-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.authentik.token.value | quote }}
{{- end }}
